### YamlMime:ManagedReference
items:
- uid: Diploma.Application.Predictions
  id: Predictions
  parent: Diploma.Application
  children:
  - Diploma.Application.Predictions.Factories.Interfaces
  - Diploma.Application.Predictions.Interfaces
  - Diploma.Application.Predictions.Queries.PredictPrice
  langs:
  - csharp
  - vb
  name: Diploma.Application.Predictions
  type: Namespace
references:
- uid: Diploma.Application.Predictions.Interfaces
  commentId: N:Diploma.Application.Predictions.Interfaces
  href: Diploma.html
  name: Diploma.Application.Predictions.Interfaces
  nameWithType: Diploma.Application.Predictions.Interfaces
  fullName: Diploma.Application.Predictions.Interfaces
  spec.csharp:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Interfaces.html
  spec.vb:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Interfaces.html
- uid: Diploma.Application.Predictions.Factories.Interfaces
  commentId: N:Diploma.Application.Predictions.Factories.Interfaces
  href: Diploma.html
  name: Diploma.Application.Predictions.Factories.Interfaces
  nameWithType: Diploma.Application.Predictions.Factories.Interfaces
  fullName: Diploma.Application.Predictions.Factories.Interfaces
  spec.csharp:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories
    name: Factories
    href: Diploma.Application.Predictions.Factories.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Factories.Interfaces.html
  spec.vb:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories
    name: Factories
    href: Diploma.Application.Predictions.Factories.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Factories.Interfaces.html
- uid: Diploma.Application.Predictions.Queries.PredictPrice
  commentId: N:Diploma.Application.Predictions.Queries.PredictPrice
  href: Diploma.html
  name: Diploma.Application.Predictions.Queries.PredictPrice
  nameWithType: Diploma.Application.Predictions.Queries.PredictPrice
  fullName: Diploma.Application.Predictions.Queries.PredictPrice
  spec.csharp:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Queries
    name: Queries
    href: Diploma.Application.Predictions.Queries.html
  - name: .
  - uid: Diploma.Application.Predictions.Queries.PredictPrice
    name: PredictPrice
    href: Diploma.Application.Predictions.Queries.PredictPrice.html
  spec.vb:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Queries
    name: Queries
    href: Diploma.Application.Predictions.Queries.html
  - name: .
  - uid: Diploma.Application.Predictions.Queries.PredictPrice
    name: PredictPrice
    href: Diploma.Application.Predictions.Queries.PredictPrice.html
