### YamlMime:ManagedReference
items:
- uid: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory
  commentId: T:Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory
  id: IPredictionRepositoryFactory
  parent: Diploma.Application.Predictions.Factories.Interfaces
  children:
  - Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository(Diploma.Domain.Models.ModelType)
  langs:
  - csharp
  - vb
  name: IPredictionRepositoryFactory
  nameWithType: IPredictionRepositoryFactory
  fullName: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory
  type: Interface
  source:
    remote:
      path: Diploma.Application/Predictions/Factories/Interfaces/IPredictionRepositoryFactory.cs
      branch: documantation
      repo: https://github.com/51xel/Diploma.git
    id: IPredictionRepositoryFactory
    path: Diploma.Application/Predictions/Factories/Interfaces/IPredictionRepositoryFactory.cs
    startLine: 5
  assemblies:
  - Diploma.Application
  namespace: Diploma.Application.Predictions.Factories.Interfaces
  syntax:
    content: public interface IPredictionRepositoryFactory
    content.vb: Public Interface IPredictionRepositoryFactory
- uid: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository(Diploma.Domain.Models.ModelType)
  commentId: M:Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository(Diploma.Domain.Models.ModelType)
  id: GetPredictionRepository(Diploma.Domain.Models.ModelType)
  parent: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory
  langs:
  - csharp
  - vb
  name: GetPredictionRepository(ModelType)
  nameWithType: IPredictionRepositoryFactory.GetPredictionRepository(ModelType)
  fullName: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository(Diploma.Domain.Models.ModelType)
  type: Method
  source:
    remote:
      path: Diploma.Application/Predictions/Factories/Interfaces/IPredictionRepositoryFactory.cs
      branch: documantation
      repo: https://github.com/51xel/Diploma.git
    id: GetPredictionRepository
    path: Diploma.Application/Predictions/Factories/Interfaces/IPredictionRepositoryFactory.cs
    startLine: 7
  assemblies:
  - Diploma.Application
  namespace: Diploma.Application.Predictions.Factories.Interfaces
  syntax:
    content: IPredictionRepository GetPredictionRepository(ModelType modelType)
    parameters:
    - id: modelType
      type: Diploma.Domain.Models.ModelType
    return:
      type: Diploma.Application.Predictions.Interfaces.IPredictionRepository
    content.vb: Function GetPredictionRepository(modelType As ModelType) As IPredictionRepository
  overload: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository*
references:
- uid: Diploma.Application.Predictions.Factories.Interfaces
  commentId: N:Diploma.Application.Predictions.Factories.Interfaces
  href: Diploma.html
  name: Diploma.Application.Predictions.Factories.Interfaces
  nameWithType: Diploma.Application.Predictions.Factories.Interfaces
  fullName: Diploma.Application.Predictions.Factories.Interfaces
  spec.csharp:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories
    name: Factories
    href: Diploma.Application.Predictions.Factories.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Factories.Interfaces.html
  spec.vb:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories
    name: Factories
    href: Diploma.Application.Predictions.Factories.html
  - name: .
  - uid: Diploma.Application.Predictions.Factories.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Factories.Interfaces.html
- uid: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository*
  commentId: Overload:Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository
  href: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.html#Diploma_Application_Predictions_Factories_Interfaces_IPredictionRepositoryFactory_GetPredictionRepository_Diploma_Domain_Models_ModelType_
  name: GetPredictionRepository
  nameWithType: IPredictionRepositoryFactory.GetPredictionRepository
  fullName: Diploma.Application.Predictions.Factories.Interfaces.IPredictionRepositoryFactory.GetPredictionRepository
- uid: Diploma.Domain.Models.ModelType
  commentId: T:Diploma.Domain.Models.ModelType
  parent: Diploma.Domain.Models
  href: Diploma.Domain.Models.ModelType.html
  name: ModelType
  nameWithType: ModelType
  fullName: Diploma.Domain.Models.ModelType
- uid: Diploma.Application.Predictions.Interfaces.IPredictionRepository
  commentId: T:Diploma.Application.Predictions.Interfaces.IPredictionRepository
  parent: Diploma.Application.Predictions.Interfaces
  href: Diploma.Application.Predictions.Interfaces.IPredictionRepository.html
  name: IPredictionRepository
  nameWithType: IPredictionRepository
  fullName: Diploma.Application.Predictions.Interfaces.IPredictionRepository
- uid: Diploma.Domain.Models
  commentId: N:Diploma.Domain.Models
  href: Diploma.html
  name: Diploma.Domain.Models
  nameWithType: Diploma.Domain.Models
  fullName: Diploma.Domain.Models
  spec.csharp:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Domain
    name: Domain
    href: Diploma.Domain.html
  - name: .
  - uid: Diploma.Domain.Models
    name: Models
    href: Diploma.Domain.Models.html
  spec.vb:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Domain
    name: Domain
    href: Diploma.Domain.html
  - name: .
  - uid: Diploma.Domain.Models
    name: Models
    href: Diploma.Domain.Models.html
- uid: Diploma.Application.Predictions.Interfaces
  commentId: N:Diploma.Application.Predictions.Interfaces
  href: Diploma.html
  name: Diploma.Application.Predictions.Interfaces
  nameWithType: Diploma.Application.Predictions.Interfaces
  fullName: Diploma.Application.Predictions.Interfaces
  spec.csharp:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Interfaces.html
  spec.vb:
  - uid: Diploma
    name: Diploma
    href: Diploma.html
  - name: .
  - uid: Diploma.Application
    name: Application
    href: Diploma.Application.html
  - name: .
  - uid: Diploma.Application.Predictions
    name: Predictions
    href: Diploma.Application.Predictions.html
  - name: .
  - uid: Diploma.Application.Predictions.Interfaces
    name: Interfaces
    href: Diploma.Application.Predictions.Interfaces.html
